[build]
publish = "dist"
command = "npm run build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

# Add these redirects to route to your function subdirectories
[[redirects]]
from = "/.netlify/functions/auth-login"
to = "/.netlify/functions/auth/login"
status = 200

[[redirects]]
from = "/.netlify/functions/auth-register"
to = "/.netlify/functions/auth/register"
status = 200